### ISSUE TITLE
标注表格数据生成的gt.txt无法通过PaddleX 表格训练的验证

### ISSUE THREAD

**Issue by Bb91234567890** [PFCCLab/PPOCRLabel#118]
生成的gt.txt跟原来的表格不一样
原来的表格：
![Image](https://github.com/user-attachments/assets/0c69059a-26cf-4ff1-8a20-e6f29c010ce6)

gt.txt中gt属性 加线框后的html：
![Image](https://github.com/user-attachments/assets/739f2714-d151-4aba-bacf-faf25a85969f)

gt.txt （为了满足训练格式，手动加了‘images/’表示路径）：
[gt.txt](https://github.com/user-attachments/files/17915056/gt.txt)

验证数据集：
![Image](https://github.com/user-attachments/assets/e0496623-ba6e-4dd7-bad0-a82efa9ae824)

验证数据集命令：
python main.py -c paddlex/configs/table_recognition/SLANet_plus.yaml \
    -o Global.mode=check_dataset \
    -o Global.dataset_dir=/home/aistudio/PaddleX/train_data

验证失败出现的错误：
aistudio@jupyter-13749311-8523997:~/PaddleX$ python main.py -c paddlex/configs/table_recognition/SLANet_plus.yaml     -o Global.mode=check_dataset     -o Global.dataset_dir=/home/aistudio/PaddleX/train_data
        Traceback (most recent call last):
  File "/home/aistudio/PaddleX/paddlex/utils/result_saver.py", line 29, in wrap
    result = func(self, *args, **kwargs)
  File "/home/aistudio/PaddleX/paddlex/engine.py", line 38, in run
    return self._model.check_dataset()
  File "/home/aistudio/PaddleX/paddlex/model.py", line 90, in check_dataset
    return dataset_checker.check()
  File "/home/aistudio/PaddleX/paddlex/modules/base/dataset_checker/dataset_checker.py", line 75, in check
    attrs = self.check_dataset(dataset_dir)
  File "/home/aistudio/PaddleX/paddlex/modules/table_recognition/dataset_checker/__init__.py", line 67, in check_dataset
    return check(dataset_dir, self.global_config.output, sample_num=10)
  File "/home/aistudio/PaddleX/paddlex/modules/table_recognition/dataset_checker/dataset_src/check_dataset.py", line 75, in check
    raise CheckFailedError(
paddlex.utils.errors.dataset_checker.CheckFailedError: Check dataset failed. We encountered the following error:
  The number of cells needs to be consistent with the number of tokens but the number of cells is {boxes_num}, and the number of tokens is {tokens_num}.

**Comment by GreatV** [comment]
检查一下标注和excel

**Comment by Bb91234567890** [comment]
> 检查一下标注和excel

标注
![Image](https://github.com/user-attachments/assets/98006e12-c97e-4dbe-98c0-d35e39a722cf)
自动打开的excel没有文字，但是有些单元格是合并了的，然后我自己填充数据可以吗

**Comment by GreatV** [comment]
是的

**Comment by GreatV** [comment]
你给paddlex提个issue吧

**Comment by Bb91234567890** [comment]
> 你给paddlex提个issue吧

之前提过了，大概意思是数据不对.我想应该还是这边标注的问题，这个识别出来的结果和表格不一致，就算能训练了，训练效果应该也会很受影响吧.我这个paddlelabel 2.1.3 paddleocr2.7.3 paddlepaddle2.5.2版本太低了吗，可是换成高版本，弹出的excel没有内容，只有一些合并单元格.

**Comment by GreatV** [comment]
降低版本以后不是能对应上吗

**Comment by Bb91234567890** [comment]
> 降低版本以后不是能对应上吗

excel是能对应上，但是导出的gt.txt还是对不上，里面的html加线框后长这样
![Image](https://github.com/user-attachments/assets/4d4f7936-e50d-4b19-ac06-5072b458065d)

**Comment by GreatV** [comment]
麻烦提供一下原图，我后面看下是不是bug。

**Comment by Bb91234567890** [comment]
好的，这几天尝试发现好像需要手动调整excel的，都是有问题的

**Comment by Bb91234567890** [comment]
![Image](https://github.com/user-attachments/assets/198632fa-343c-43d1-9d3d-71c134cd94e8)

**Comment by BotAndyGao** [comment]
> > 你给paddlex提个issue吧
> 
> 之前提过了，大概意思是数据不对.我想应该还是这边标注的问题，这个识别出来的结果和表格不一致，就算能训练了，训练效果应该也会很受影响吧.我这个paddlelabel 2.1.3 paddleocr2.7.3 paddlepaddle2.5.2版本太低了吗，可是换成高版本，弹出的excel没有内容，只有一些合并单元格.

## 以下的环境配置已经验证没有问题，服务发布Paddle的版本可以升级为3.0都没有问题。
### 标注环境
- Paddle版本：2.5.2
- PPOCRLabel版本：release/2.1.11， 安装方式：源码
### 训练环境
- Paddle版本：2.6.1， 安装方式：Docker
- PaddleOCR版本：release/2.8， 安装方式：源码

## 标注问题
如果报The number of cells needs to be consistent with the number of tokens but the number of cells is {boxes_num}, and the number of tokens is {tokens_num}. 只有一个原因就是标注的单元格和Excel调整的格式不匹配。
### 检查点
1、单元格顺序和excel要匹配
2、excel除了表格外，把横、纵行都都多删除一些，然后保存，导出。

**Comment by BotAndyGao** [comment]
> 好的，这几天尝试发现好像需要手动调整excel的，都是有问题的

你的这个图片自动识别后，excel是三行四列，但是第四行有一个合并，需要手动删除，导出就可以了。注意：最好把横、纵行都删除一些。这个不是bug，因为标注系统是以excel为准的，而execel是人来确定的，所以系统是无法自动感知的，所以必须是人来调整。

**Comment by Bb91234567890** [comment]
> > 好的，这几天尝试发现好像需要手动调整excel的，都是有问题的
> 
> 你的这个图片自动识别后，excel是三行四列，但是第四行有一个合并，需要手动删除，导出就可以了。注意：最好把横、纵行都删除一些。这个不是bug，因为标注系统是以excel为准的，而execel是人来确定的，所以系统是无法自动感知的，所以必须是人来调整。

![Image](https://github.com/user-attachments/assets/1ac0b238-5c76-450b-8492-3aa06ce5f5fc) 不行，我发现我怎么改excel导出的gt.txt内容都是一样的，删了gt.txt和对应的excel，重新表格识别，修改excel，保存，导出gt.txt，还是不行，原本有些正确标注的图片，我故意在excel多加几个 合并单元格，导出的gt.txt还是没有变化

**Comment by BotAndyGao** [comment]
> > > 好的，这几天尝试发现好像需要手动调整excel的，都是有问题的
> > 
> > 
> > 你的这个图片自动识别后，excel是三行四列，但是第四行有一个合并，需要手动删除，导出就可以了。注意：最好把横、纵行都删除一些。这个不是bug，因为标注系统是以excel为准的，而execel是人来确定的，所以系统是无法自动感知的，所以必须是人来调整。
> 
> ![Image](https://github.com/user-attachments/assets/1ac0b238-5c76-450b-8492-3aa06ce5f5fc) 不行，我发现我怎么改excel导出的gt.txt内容都是一样的，删了gt.txt和对应的excel，重新表格识别，修改excel，保存，导出gt.txt，还是不行，原本有些正确标注的图片，我故意在excel多加几个 合并单元格，导出的gt.txt还是没有变化

### 已经使用PPOCRLabel2.1.11标注了你的图片并且导出标注，完成了训练。

-  正确的标注导出，看一下你的导出，和这个一样就可以训练。
```plaintext
{"filename": "test1.png", "html": {"structure": {"tokens": ["<tbody>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "</tbody>"]}, "cells": [{"tokens": ["序", "号"], "bbox": [[148, 50], [230, 50], [230, 92], [148, 92]]}, {"tokens": ["产", "品", "名", "称"], "bbox": [[505, 50], [671, 50], [671, 92], [505, 92]]}, {"tokens": ["H", "S", " ", "编", "码"], "bbox": [[1028, 53], [1177, 53], [1177, 95], [1028, 95]]}, {"tokens": ["规", "格", "型", "号"], "bbox": [[1514, 50], [1678, 50], [1678, 92], [1514, 92]]}, {"tokens": ["1"], "bbox": [[173, 99], [201, 99], [201, 137], [173, 137]]}, {"tokens": ["有", "接", "头", "电", "导", "体"], "bbox": [[471, 97], [702, 97], [702, 137], [471, 137]]}, {"tokens": ["8", "5", "4", "4", "4", "2", "2", "9", "0", "0"], "bbox": [[1006, 102], [1200, 102], [1200, 135], [1006, 135]]}, {"tokens": ["M", "0", "1", "0", "1", "0", "1", "0", "2", "4", "0"], "bbox": [[1488, 102], [1702, 102], [1702, 135], [1488, 135]]}, {"tokens": ["2"], "bbox": [[173, 144], [201, 144], [201, 182], [173, 182]]}, {"tokens": ["接", "插", "件"], "bbox": [[524, 142], [646, 142], [646, 184], [524, 184]]}, {"tokens": ["8", "5", "3", "6", "6", "9", "0", "0", "0", "0"], "bbox": [[1004, 144], [1202, 144], [1202, 184], [1004, 184]]}, {"tokens": ["M", "0", "1", "0", "5", "0", "3", "1", "4", "3", "0"], "bbox": [[1490, 146], [1704, 146], [1704, 179], [1490, 179]]}]}, "gt": "<html><body><table><tbody><tr><td>序号</td><td>产品名称</td><td>HS 编码</td><td>规格型号</td></tr><tr><td>1</td><td>有接头电导体</td><td>8544422900</td><td>M0101010240</td></tr><tr><td>2</td><td>接插件</td><td>8536690000</td><td>M0105031430</td></tr></tbody></table></body></html>"}
``` 
- 正确训练截图，可以看到第一轮所有的62个批次都跑完了，没有报错。
![Image](https://github.com/user-attachments/assets/2a97bb18-3b38-413a-90e0-2bc48976ff5d)

### 问题
- 你如果带着第四行的单元格，那么structure的tokens就会多一行，而你的标注框是没有这行的，所以训练时会报错，训练代码会严格检查顺序对应关系。

### 标注之所以需要Excel那是因为标注系统是无法感知图片的结构的，也就是行、列和合并，这些都要由Excel来实现，标注系统才能根据Excel和标注框来合成标注报文，之所以要规定标注框的顺序也是为了对应Excel，保证训练时使用的标注数据是真实还原图片表格的，所以Excel的调整是必须的，而且这个只能是标注人来调整，因为只有标注人才能看的懂图片的表格结构。

**Comment by Bb91234567890** [comment]
> > > > 好的，这几天尝试发现好像需要手动调整excel的，都是有问题的
> > > 
> > > 
> > > 你的这个图片自动识别后，excel是三行四列，但是第四行有一个合并，需要手动删除，导出就可以了。注意：最好把横、纵行都删除一些。这个不是bug，因为标注系统是以excel为准的，而execel是人来确定的，所以系统是无法自动感知的，所以必须是人来调整。
> > 
> > 
> > ![Image](https://github.com/user-attachments/assets/1ac0b238-5c76-450b-8492-3aa06ce5f5fc) 不行，我发现我怎么改excel导出的gt.txt内容都是一样的，删了gt.txt和对应的excel，重新表格识别，修改excel，保存，导出gt.txt，还是不行，原本有些正确标注的图片，我故意在excel多加几个 合并单元格，导出的gt.txt还是没有变化
> 
> ### 已经使用PPOCRLabel2.1.11标注了你的图片并且导出标注，完成了训练。
> * 正确的标注导出，看一下你的导出，和这个一样就可以训练。
> 
> ```
> {"filename": "test1.png", "html": {"structure": {"tokens": ["<tbody>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "</tbody>"]}, "cells": [{"tokens": ["序", "号"], "bbox": [[148, 50], [230, 50], [230, 92], [148, 92]]}, {"tokens": ["产", "品", "名", "称"], "bbox": [[505, 50], [671, 50], [671, 92], [505, 92]]}, {"tokens": ["H", "S", " ", "编", "码"], "bbox": [[1028, 53], [1177, 53], [1177, 95], [1028, 95]]}, {"tokens": ["规", "格", "型", "号"], "bbox": [[1514, 50], [1678, 50], [1678, 92], [1514, 92]]}, {"tokens": ["1"], "bbox": [[173, 99], [201, 99], [201, 137], [173, 137]]}, {"tokens": ["有", "接", "头", "电", "导", "体"], "bbox": [[471, 97], [702, 97], [702, 137], [471, 137]]}, {"tokens": ["8", "5", "4", "4", "4", "2", "2", "9", "0", "0"], "bbox": [[1006, 102], [1200, 102], [1200, 135], [1006, 135]]}, {"tokens": ["M", "0", "1", "0", "1", "0", "1", "0", "2", "4", "0"], "bbox": [[1488, 102], [1702, 102], [1702, 135], [1488, 135]]}, {"tokens": ["2"], "bbox": [[173, 144], [201, 144], [201, 182], [173, 182]]}, {"tokens": ["接", "插", "件"], "bbox": [[524, 142], [646, 142], [646, 184], [524, 184]]}, {"tokens": ["8", "5", "3", "6", "6", "9", "0", "0", "0", "0"], "bbox": [[1004, 144], [1202, 144], [1202, 184], [1004, 184]]}, {"tokens": ["M", "0", "1", "0", "5", "0", "3", "1", "4", "3", "0"], "bbox": [[1490, 146], [1704, 146], [1704, 179], [1490, 179]]}]}, "gt": "<html><body><table><tbody><tr><td>序号</td><td>产品名称</td><td>HS 编码</td><td>规格型号</td></tr><tr><td>1</td><td>有接头电导体</td><td>8544422900</td><td>M0101010240</td></tr><tr><td>2</td><td>接插件</td><td>8536690000</td><td>M0105031430</td></tr></tbody></table></body></html>"}
> ```
> 
> * 正确训练截图，可以看到第一轮所有的62个批次都跑完了，没有报错。（训练机的时间比当前时间少了8个小时）
>   ![Image](https://github.com/user-attachments/assets/2a97bb18-3b38-413a-90e0-2bc48976ff5d)
> 
> ### 问题
> * 你如果带着第四行的单元格，那么structure的tokens就会多一行，而你的标注框是没有这行的，所以训练时会报错，训练代码会严格检查顺序对应关系。
> 
> ### 标注之所以需要Excel那是因为标注系统是无法感知图片的结构的，也就是行、列和合并，这些都要由Excel来实现，标注系统才能根据Excel和标注框来合成标注报文，之所以要规定标注框的顺序也是为了对应Excel，保证训练时使用的标注数据是真实还原图片表格的，所以Excel的调整是必须的，而且这个只能是标注人来调整，因为只有标注人才能看的懂图片的表格结构。

我理解大佬您的意思，就是训练的表格结构是由excel决定的，问题就是我按照表格结构调整excel不生效呐

**Comment by BotAndyGao** [comment]
哈哈，这个就没办法解释了，我刚才又试了一下，调整Excel应该是生效的。

```plaintext
# 错误结构报文
{"filename": "test1.png", "html": {"structure": {"tokens": ["<tbody>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td", " colspan=\"3\"", ">", "</td>", "<td>", "</td>", "</tr>", "</tbody>"]}, "cells": [{"tokens": ["序", "号"], "bbox": [[148, 50], [230, 50], [230, 92], [148, 92]]}, {"tokens": ["产", "品", "名", "称"], "bbox": [[505, 50], [671, 50], [671, 92], [505, 92]]}, {"tokens": ["H", "S", " ", "编", "码"], "bbox": [[1028, 53], [1177, 53], [1177, 95], [1028, 95]]}, {"tokens": ["规", "格", "型", "号"], "bbox": [[1514, 50], [1678, 50], [1678, 92], [1514, 92]]}, {"tokens": ["1"], "bbox": [[173, 99], [201, 99], [201, 137], [173, 137]]}, {"tokens": ["有", "接", "头", "电", "导", "体"], "bbox": [[471, 97], [702, 97], [702, 137], [471, 137]]}, {"tokens": ["8", "5", "4", "4", "4", "2", "2", "9", "0", "0"], "bbox": [[1006, 102], [1200, 102], [1200, 135], [1006, 135]]}, {"tokens": ["M", "0", "1", "0", "1", "0", "1", "0", "2", "4", "0"], "bbox": [[1488, 102], [1702, 102], [1702, 135], [1488, 135]]}, {"tokens": ["2"], "bbox": [[173, 144], [201, 144], [201, 182], [173, 182]]}, {"tokens": ["接", "插", "件"], "bbox": [[524, 142], [646, 142], [646, 184], [524, 184]]}, {"tokens": ["8", "5", "3", "6", "6", "9", "0", "0", "0", "0"], "bbox": [[1004, 144], [1202, 144], [1202, 184], [1004, 184]]}, {"tokens": ["M", "0", "1", "0", "5", "0", "3", "1", "4", "3", "0"], "bbox": [[1490, 146], [1704, 146], [1704, 179], [1490, 179]]}]}, "gt": "<html><body><table><tbody><tr><td></td><td></td><td>序号</td><td>产品名称</td></tr><tr><td>HS 编码</td><td>规格型号</td><td>1</td><td>有接头电导体</td></tr><tr><td>8544422900</td><td>M0101010240</td><td>2</td><td>接插件</td></tr><tr><td colspan=3>8536690000</td><td>M0105031430</td></tr></tbody></table></body></html>"}

# 正确格式报文
{"filename": "test1.png", "html": {"structure": {"tokens": ["<tbody>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "<tr>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "<td>", "</td>", "</tr>", "</tbody>"]}, "cells": [{"tokens": ["序", "号"], "bbox": [[148, 50], [230, 50], [230, 92], [148, 92]]}, {"tokens": ["产", "品", "名", "称"], "bbox": [[505, 50], [671, 50], [671, 92], [505, 92]]}, {"tokens": ["H", "S", " ", "编", "码"], "bbox": [[1028, 53], [1177, 53], [1177, 95], [1028, 95]]}, {"tokens": ["规", "格", "型", "号"], "bbox": [[1514, 50], [1678, 50], [1678, 92], [1514, 92]]}, {"tokens": ["1"], "bbox": [[173, 99], [201, 99], [201, 137], [173, 137]]}, {"tokens": ["有", "接", "头", "电", "导", "体"], "bbox": [[471, 97], [702, 97], [702, 137], [471, 137]]}, {"tokens": ["8", "5", "4", "4", "4", "2", "2", "9", "0", "0"], "bbox": [[1006, 102], [1200, 102], [1200, 135], [1006, 135]]}, {"tokens": ["M", "0", "1", "0", "1", "0", "1", "0", "2", "4", "0"], "bbox": [[1488, 102], [1702, 102], [1702, 135], [1488, 135]]}, {"tokens": ["2"], "bbox": [[173, 144], [201, 144], [201, 182], [173, 182]]}, {"tokens": ["接", "插", "件"], "bbox": [[524, 142], [646, 142], [646, 184], [524, 184]]}, {"tokens": ["8", "5", "3", "6", "6", "9", "0", "0", "0", "0"], "bbox": [[1004, 144], [1202, 144], [1202, 184], [1004, 184]]}, {"tokens": ["M", "0", "1", "0", "5", "0", "3", "1", "4", "3", "0"], "bbox": [[1490, 146], [1704, 146], [1704, 179], [1490, 179]]}]}, "gt": "<html><body><table><tbody><tr><td>序号</td><td>产品名称</td><td>HS 编码</td><td>规格型号</td></tr><tr><td>1</td><td>有接头电导体</td><td>8544422900</td><td>M0101010240</td></tr><tr><td>2</td><td>接插件</td><td>8536690000</td><td>M0105031430</td></tr></tbody></table></body></html>"}
```
- 错误Excel截图
![Image](https://github.com/user-attachments/assets/e6183666-8dcc-400e-ab08-b4bb5ac8043d)

- 调整正确Excel截图（调整后要保存excel，再导出）
![Image](https://github.com/user-attachments/assets/4e29c726-6ad8-4035-8940-4574fdda849f)

**Comment by carlos-yuan** [comment]
相同问题，这里应该弹出具体是哪个有问题会好些，数据集里面内容过多，除非去代码里面打断点，这会比较麻烦

**Comment by carlos-yuan** [comment]
![Image](https://github.com/user-attachments/assets/f1780ac5-1471-49fa-a522-961bddf465cb)

**Comment by BotAndyGao** [comment]
> ![Image](https://github.com/user-attachments/assets/f1780ac5-1471-49fa-a522-961bddf465cb)

你这个是paddlex的训练日志吧？可以给paddlex提一个issues，显示出是哪张训练图片出问题，在PaddleOCR里训练报错是会显示哪张图片出问题的。

![Image](https://github.com/user-attachments/assets/6647ace7-7fa7-47d4-94cb-0a1a404d81ae)

**Comment by Bb91234567890** [comment]
已经成功完成训练，我的操作：ctrl a删除所有excel单元格内容，然后根据表格手动填充数据，来保持和图片一样的结构
