### ISSUE TITLE
表格标注 顺序的序号是如何显示的

### ISSUE THREAD

**Issue by 77bw** [PFCCLab/PPOCRLabel#12]
![image](https://github.com/PFCCLab/PPOCRLabel/assets/94338396/9564ed52-57d2-4bae-8f47-6728a62eb8db)

**Comment by GreatV** [comment]
https://github.com/PFCCLab/PPOCRLabel/blob/bfa0d5992747e2492a6bf72e347d3786552e350a/PPOCRLabel.py#L2879-L2903
