### ISSUE TITLE
PPOCRLabel --lang ch --kie True 下绘制矩形标注框导致程序崩坏

### ISSUE THREAD

**Issue by TTTalen** [PFCCLab/PPOCRLabel#13]
传入坐标信息时，期待传入类型为int，但是传入了float类型。
pyANACONDA\envs\feijiang_label\lib\site-packages\PPOCRLabel\PPOCRLabel.py line 1425
原始代码为
bar.setValue(bar.value() + bar.singleStep() * units)
更改后为
bar.setValue(int(bar.value() + bar.singleStep() * units))

pyANACONDA\envs\feijiang_label\lib\site-packages\PPOCRLabel\libs\canvas.py line 596
原始代码为
p.drawRect(leftTop.x(), leftTop.y(), rectWidth, rectHeight)
更改后为
p.drawRect(int(leftTop.x()), int(leftTop.y()), int(rectWidth), int(rectHeight))

**Comment by GreatV** [comment]
@TTTalen 欢迎提一个PR来修复这个问题

**Comment by TTTalen** [comment]
> @TTTalen 欢迎提一个PR来修复这个问题

该问题源代码中已经修复。问题来源为使用pip从第三方源安装时导致。

**Comment by GreatV** [comment]
@TTTalen 谢谢确认，在使用过程中有任何问题，都欢迎提PR来修复。
