### ISSUE TITLE
將PPOCRLabel轉exe後發生ImportError: cannot import name 'DEFAULT_LOCK_COLOR' from 'libs.shape' 。

### ISSUE THREAD

**Issue by DingHsun** [PFCCLab/PPOCRLabel#15]
问题描述 / Problem Description
使用pyinstaller將PPOCRLabel轉exe，生成dist資料夾，內部包含執行檔PPOCRLabel.exe及資料夾_internal。
已參考https://blog.csdn.net/u012254599/article/details/128012719 將所需套件放入後，再將PPOCRLabel-main\libs放入_internal內。
運行PPOCRLabel.exe發生
ImportError: cannot import name 'DEFAULT_LOCK_COLOR' from 'libs.shape' (D:\OCR\PaddleOCR env\PPOCRLabel-main\dist\PPOCRLabel\_internal\libs\shape.pyc)。

运行环境 / Runtime Environment
OS : Win10
paddlepaddle : 2.5.1
paddleocr : 2.6
PaddleOCR : PaddleOCR-release-2.7

完整报错 / Complete Error Message
Traceback (most recent call last):
  File "PPOCRLabel-main\PPOCRLabel.py", line 77, in <module>
ImportError: cannot import name 'DEFAULT_LOCK_COLOR' from 'libs.shape' (D:\OCR\PaddleOCR env\PPOCRLabel-main\dist\PPOCRLabel\_internal\libs\shape.pyc)

求各位大佬幫忙解決!!!

**Comment by GreatV** [comment]
Perhaps you could refer to:
- https://github.com/PaddlePaddle/PaddleOCR/discussions/11342

**Comment by Gmgge** [comment]
由于资源加载时，该形式的[路径](https://github.com/PFCCLab/PPOCRLabel/blob/bfa0d5992747e2492a6bf72e347d3786552e350a/libs/stringBundle.py#L23)资源配置，导致打包后无法正常加载到该资源，目前正在修复中。
