### ISSUE TITLE
标注矩形框时报错.

### ISSUE THREAD

**Issue by durongzheng** [PFCCLab/PPOCRLabel#17]
我的环境是win11专业版，python 3.10.10, cpu 版的 paddleocr。运行 paddlelabel 命令如下：
` PPOCRLabel --lang ch --kie True`
 
标注矩形框时，报以下错误：
Traceback (most recent call last):
  File "D:\myCode\python\venv\lib\site-packages\PPOCRLabel\libs\canvas.py", line 596, in paintEvent
    p.drawRect(leftTop.x(), leftTop.y(), rectWidth, rectHeight)
TypeError: arguments did not match any overloaded call:
  drawRect(self, rect: QRectF): argument 1 has unexpected type 'float'
  drawRect(self, x: int, y: int, w: int, h: int): argument 1 has unexpected type 'float'
  drawRect(self, r: QRect): argument 1 has unexpected type 'float'
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?

怎么解决呢？

**Comment by GreatV** [comment]
加上`int(leftTop.x()) ...`

**Comment by durongzheng** [comment]
对了。谢谢！

> 加上`int(leftTop.x()) ...`

**Comment by Gmgge** [comment]
@GreatV 我想是否应该为此提交pr，这些类型触发的闪退bug中，通常是因为不再能隐式转换导致类型不匹配，为了更好的版本兼容，可以添加显式类型转换。
