### ISSUE TITLE
python打开出现问题

### ISSUE THREAD

**Issue by Myles091** [PFCCLab/PPOCRLabel#19]
[2024/06/20 15:45:19] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false

ValueError: operands could not be broadcast together with shapes (213,488,4) (1,1,3)

这是咋回事啊

**Comment by GreatV** [comment]
paddleocr的版本是多少呀

**Comment by Gmgge** [comment]
paddleocr版本降级，目前请安装pip install paddleocr==2.6.1.3

**Comment by Myles091** [comment]
> paddleocr的版本是多少呀

Name: paddleocr
Version: 2.7.3

**Comment by Myles091** [comment]
paddleocr              2.7.3
paddlepaddle-gpu       2.6.1.post117

这是具体的版本，尝试了2.6好像也不太行

**Comment by Gmgge** [comment]
@Myles091 你好，可以贴下最新的报错吗？
需要确认的是：
1.是否使用当前最新的PPOCRLabel，而非先前嵌入在paddleocr项目中的PPOCRLabel，排除import 到本地项目中的旧代码
2.可以的话贴下更详细的日志，这边暂时无法在2.6.1.3版本复现出这个报错。

**Comment by qdhonker** [comment]
> pypi发布的paddleocr目前版本有个四通道图像处理问题，当前有两种方案： 1.安装pip install paddleocr==2.6.1.3 2.源码安装最新的paadleocr
> 
> 期待你的测试反馈

安装paddleocr==2.6.1.3 可以解决问题
