### ISSUE TITLE
PPOCRLabel标注使用中文输入法异常

### ISSUE THREAD

**Issue by 77bw** [PFCCLab/PPOCRLabel#20]
运行环境 / Runtime Environment
python 3.8
paddlepaddle==2.5.0
PPOCRLabel==2.1.3

直接从官方文档的环境下载也不行,使用编辑文字秒切英文

https://github.com/PFCCLab/PPOCRLabel/assets/94338396/cbc45bc2-a35f-4a2d-b84d-453f6fe3e71d

**Comment by Gmgge** [comment]
你好，由于PPOCRLabel已经从paddleocr项目迁出，新版本尚未发布whl包，你是否可以测试下最新版本？
我这边环境是：
paddleocr                 2.6.1.3
paddlepaddle              2.6.1
源码启动没有复现这个问题。

**Comment by Gmgge** [comment]
这边再次更换了机器，测试了python3.8、3.9环境，windows下可以正常切换输入法，有任何进一步的报错欢迎反馈。

**Comment by 77bw** [comment]
你好这边已经解决了，直接用你们这个本地代码即可。可能是我下载whl包的问题。
![image](https://github.com/PFCCLab/PPOCRLabel/assets/94338396/48011ff5-4f0c-425e-8d64-642c075ae58d)
另外ni你们源码这块需要将这块注释了才正常运行

**Comment by GreatV** [comment]
@Gmgge 我们是不是可以换一个启动检测的图，换成三通道的。

**Comment by Gmgge** [comment]
可以的，不过目前来说就算修改成三通道图像，万一遇到待标注的图像是四通道任然会导致图像闪退，这是非常影响体验的情况。

我个人来说，不建议降低自测的条件从而达到通过测试条件的措施，当前最优的还是推进paddleocr推出新版本whl包，该问题已经修复一段时间了，也许可以在明天会议里讨论下新的paddleocr whl的推送问题？需要那些前置工作什么的
