### ISSUE TITLE
The specified module was not found

### ISSUE THREAD

**Issue by omeeragtoprak** [PFCCLab/PPOCRLabel#24]
ImportError: DLL load failed while importing libpaddle: Belirtilen modül bulunamadı.

**Comment by Gmgge** [comment]
@omeeragtoprak  你好，有更详细的描述吗？方便的话，提供以下消息以供复现
你的操作系统是？
你使用的paddlepaddle版本是？
你是最新的源码运行还是？
报错的上下文是否可以提供？
