### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by EphronM** [PFCCLab/PPOCRLabel#26]
Can somone please help me understand how to solve this error, seems like some issues with cv2 dependencies, but not sure what exactly is the solution

**OS:** 
ubuntu linux

**modules:**
opencv-contrib-python     4.10.0.84
opencv-python             4.10.0.84
opencv-python-headless    4.10.0.84
paddle2onnx               1.2.4
paddlefsl                 1.1.0
paddlenlp                 2.6.1
paddleocr                 2.8.0
paddlepaddle              2.6.1

**Function call**
`python PPOCRLabel.py
`

**Error:** 
QObject::moveToThread: Current thread (0x55a715570900) is not the object's thread (0x55a718b1d7b0).
Cannot move to target thread (0x55a715570900)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ubuntu/miniconda3/lib/python3.12/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1720426730 (unix time) try "date -d @1720426730" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800004ded) received by PID 19949 (TID 0x7f3b4a782740) from PID 19949 ***]

Aborted (core dumped)

**Comment by Gmgge** [comment]
1. You have too many opencv versions, please uninstall all opencv and install only one version of opencv
2. Refer to this [issue](https://github.com/NVlabs/instant-ngp/discussions/300) to try to solve it
