### ISSUE TITLE
PPOCRLabel 设置了  --kie true，对增值税发票进行要素提取的标注，怎么操作啊，求教程。

### ISSUE THREAD

**Issue by abelezm** [PFCCLab/PPOCRLabel#37]
PPOCRLabel 有文字OCR的标注教程，也比较好理解。我正在学习 教程里面的增值税发票的教程，不会里面的标注操作，也就是  kie的标注，不知道教程在哪里，我只找到了文字的标注方式的教程，要素提取的木有找到，请问老师，具体的操作步骤在哪里，实现下面这个标注，而且我看有的教程里面，还 有 link 的标注，不知道相关的操作步骤在哪里。
![image](https://github.com/user-attachments/assets/5bd7fb06-baf8-404b-9354-5ecb49451350)

**Comment by GreatV** [comment]
看一下历史issue

**Comment by abelezm** [comment]
找了所有的历史issue，也木有啥启发，是手工一行一行的修改吗，或者看那个历史issue啊，请老师指点。可否给个链接。我发现历史的issue有三个地方， 一是paddocr里面有一部分，二是之前的ppocrlabel有一部分，三是这个板块。三个板块都看了，发现2023您的issue比较多，但是还木有发现可参考的例子。恳盼老师指点。

**Comment by abelezm** [comment]
最近也参加了paddlex的课程，课程里面也木有提及标注，恳盼老师指个 方向。
