### ISSUE TITLE
找了所有的历史issue，也木有啥启发，是手工一行一行的修改吗，或者看那个历史issue，请老师指点。可否给个链接。我发现历史的issue有三个地方， 一是paddocr里面有一部分，二是之前的ppocrlabel有一部分，三是这个板块。三个板块都看了，发现2023年的issue比较多，但是还木有发现可参考的例子。恳盼老师指点。

### ISSUE THREAD

**Issue by abelezm** [PFCCLab/PPOCRLabel#40]
找了所有的历史issue，也木有啥启发，是手工一行一行的修改吗，或者看那个历史issue啊，请老师指点。可否给个链接。我发现历史的issue有三个地方， 一是paddocr里面有一部分，二是之前的ppocrlabel有一部分，三是这个板块。三个板块都看了，发现2023您的issue比较多，但是还木有发现可参考的例子。恳盼老师指点。

_Originally posted by @abelezm in https://github.com/PFCCLab/PPOCRLabel/issues/37#issuecomment-2245292192_

**Comment by GreatV** [comment]
https://aistudio.baidu.com/projectdetail/4197468

**Comment by abelezm** [comment]
谢谢老师，意外，激动，谢谢老师，这么晚还能回复，谢谢老师，
