### ISSUE TITLE
打包后无法显示图标

### ISSUE THREAD

**Issue by guanfuchen** [PFCCLab/PPOCRLabel#41]
修改libs\utils.py中的路径
def newIcon(icon, iconSize=None):
    if iconSize is not None:
        return QIcon(
            # QIcon(__iconpath__ + "/" + icon + ".png").pixmap(iconSize, iconSize)
            QIcon(":/" + icon).pixmap(iconSize, iconSize)
        )
    else:
        # return QIcon(__iconpath__ + "/" + icon + ".png")
        return QIcon(":/" + icon)

**Comment by GreatV** [comment]
欢迎提交一个PR来修复这个问题
