### ISSUE TITLE
对于图片上的文字方向不一致的，打标签时是否要有方向性？

### ISSUE THREAD

**Issue by 350050183** [PFCCLab/PPOCRLabel#42]
对于图片上的文字方向不一致的，打标签时，选择的方框或4个点，是否要有方向性？

**Comment by GreatV** [comment]
不用，框住就行。

**Comment by jg0014** [comment]
> 不用，框住就行。

您好！诚心请教，paddleocr的处理过程中有什么机制处理方向不确定带来的歧义吗？因为paddleocr的四点标注法似乎具有方向性，文字检测算法似乎也带有方向校正。在标注时没有处理方向性是否会造成训练的检测模型不准确呢。此外，在导出识别标注时，会根据检测标注的方向旋转图像，不正确的标注方向会产生方向不正确的切片结果。虽然大多数字符即使方向不正确，也可以根据特征被识别，但是部分特殊字符如“6”，“9”在方向混乱的情况下恐怕无法被正确区分
