### ISSUE TITLE
xlrd 升级到2.x 之后，不支持.xlsx

### ISSUE THREAD

**Issue by lwinhong** [PFCCLab/PPOCRLabel#45]
## 问题
  如题所述，升级到2.x之后，表格数据标注无法导出

  官方有给出说明
   [https://github.com/python-excel/xlrd](url)
   ![image](https://github.com/user-attachments/assets/6e5e9265-1a8a-404d-a4df-667134fe5dda)

## 解决方案
* 方案1. 降级到1.2.0
* 方案2. 修改源码将生成excel和到处excel的路径后缀，由 ```.xlsx``` 改为 ```.xls```，跑自己改之后的代码

  -   生成路径代码大致在：

  [https://github.com/PFCCLab/PPOCRLabel/blob/fba5f8c56dc6a4a3e54645ade08dfe168193982b/PPOCRLabel.py#L2836](url)
    ```python
    excel_path = TableRec_excel_dir + "{}.xlsx".format(filename)
   ```

  -   保存时代码路径大致在:

     [https://github.com/PFCCLab/PPOCRLabel/blob/fba5f8c56dc6a4a3e54645ade08dfe168193982b/PPOCRLabel.py#L3051](url)
    ```python
      # load csv annotations
      filename, _ = os.path.splitext(os.path.basename(image_path))
      csv_path = os.path.join(TableRec_excel_dir, filename + ".xlsx")
    ```
  -   如果是之前就已经有```.xlsx``` 格式的excel文件了，就打开直接另存为 ```.xls``` 格式

**Comment by GreatV** [comment]
欢迎提交一个PR，修改一下。

**Comment by GreatV** [comment]
@lwinhong  修复了，麻烦review一下
- #47

**Comment by lwinhong** [comment]
> @lwinhong 修复了，麻烦review一下
> 
> * [change xlrd to openpyxl #47](https://github.com/PFCCLab/PPOCRLabel/pull/47)

![27CC8A9A](https://github.com/user-attachments/assets/043e0a9f-0a49-49a5-b009-5b3f1543c339)

**Comment by lwinhong** [comment]
貌似还没合并到主线

**Comment by GreatV** [comment]
是的，需要code review，和更多测试。
