### ISSUE TITLE
换行的文字如何识别？手动输入？

### ISSUE THREAD

**Issue by PlayerJian** [PFCCLab/PPOCRLabel#46]
<img width="108" alt="屏幕截图 2024-08-05 094606" src="https://github.com/user-attachments/assets/301e0559-b205-4a57-8f7e-130962131750">
像这种换行的文字，在表格标注时是不是按整个单元格画框，但是这个框里的文字，在重新识别时，换行的只能识别第一行，下面的几行文字就要手动输入么？

**Comment by GreatV** [comment]
按行标注

**Comment by PlayerJian** [comment]
![屏幕截图 2024-08-05 180008](https://github.com/user-attachments/assets/51190293-b45d-41fe-b1d0-5cbf674e2613)
还有一个问题，标注文件里的gt部分参与训练么？因为我发现gt部分的内容完全不符合表格的版面和内容，丢失了审批单，而且排版也不一致，调试了好几次还是这样

**Comment by GreatV** [comment]
按照这个说明来 https://github.com/PFCCLab/PPOCRLabel/blob/main/README_ch.md#22-%E8%A1%A8%E6%A0%BC%E6%A0%87%E6%B3%A8%E8%A7%86%E9%A2%91%E6%BC%94%E7%A4%BA

**Comment by PlayerJian** [comment]
> 按照这个说明来 https://github.com/PFCCLab/PPOCRLabel/blob/main/README_ch.md#22-%E8%A1%A8%E6%A0%BC%E6%A0%87%E6%B3%A8%E8%A7%86%E9%A2%91%E6%BC%94%E7%A4%BA

我看到这个说明了 只是有些地方不懂 比如上面说的

**Comment by PlayerJian** [comment]
> 按照这个说明来 https://github.com/PFCCLab/PPOCRLabel/blob/main/README_ch.md#22-%E8%A1%A8%E6%A0%BC%E6%A0%87%E6%B3%A8%E8%A7%86%E9%A2%91%E6%BC%94%E7%A4%BA

2.更改标注结果：以表格中的单元格为单位增加标注框（即一个单元格内的文字都标记为一个框）
这句话我理解是，以单元格画框，但是单元格中有的文字内容有换行情况，如上我提出的，换行的话，又如我上述所说，怎么办

**Comment by PlayerJian** [comment]
> 按照这个说明来 https://github.com/PFCCLab/PPOCRLabel/blob/main/README_ch.md#22-%E8%A1%A8%E6%A0%BC%E6%A0%87%E6%B3%A8%E8%A7%86%E9%A2%91%E6%BC%94%E7%A4%BA

也就是说，有换行文字的单元格，如何进行表格标注

**Comment by GreatV** [comment]
表格一个cell只用标一个框，空白的表格也要标。

**Comment by PlayerJian** [comment]
好的，感谢

**Comment by lwinhong** [comment]
![image](https://github.com/user-attachments/assets/218677fc-b6bc-42fe-b729-b2732bcbcf97)
使用【单元格重识别】可以

**Comment by PlayerJian** [comment]
> ![image](https://private-user-images.githubusercontent.com/31954501/355307364-218677fc-b6bc-42fe-b729-b2732bcbcf97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MjU3MDksIm5iZiI6MTcyMjkyNTQwOSwicGF0aCI6Ii8zMTk1NDUwMS8zNTUzMDczNjQtMjE4Njc3ZmMtYjZiYy00MmZlLWI3MjktYjI3MzJiY2JjZjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA2MjMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZDA2NWMzZWU0MjAzZTRmODAzNTkxODEwNTMwNWM4ZDZiMGYwZWJlZjY1MzIzYjIwZGU3NjQ1ZWY1YjgzODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.575ghgbnrMsLLeEWYA7AMZriczTuBLcRdo_59IKmugg) 使用【单元格重识别】
多行文字情况下，重识别只能识别第一行，后面几行都识别不了

**Comment by PlayerJian** [comment]
> ![image](https://private-user-images.githubusercontent.com/31954501/355307364-218677fc-b6bc-42fe-b729-b2732bcbcf97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MjY4NzQsIm5iZiI6MTcyMjkyNjU3NCwicGF0aCI6Ii8zMTk1NDUwMS8zNTUzMDczNjQtMjE4Njc3ZmMtYjZiYy00MmZlLWI3MjktYjI3MzJiY2JjZjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA2NDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NzJlMjRhN2NjNzg0ZDYzYzE0NmE0MTQwYjBiZWMzNDUzZTA5ZjBmYzY1OGI2NTAwNDRmNGFkY2Y2MzE2NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QhVpUOTDL5WYULTsal6H3pXls-cabApP8HBeyNTI6Y0) 使用【单元格重识别】可以

好的 学到了 我以为单元格重识别功能 和 右上角的重新识别按钮是一个功能呢 谢谢
