### ISSUE TITLE
ubuntu安装好相关包后，启动失败。ubuntu下有具体python版本和包版本要求文件吗

### ISSUE THREAD

**Issue by kezidanbao** [PFCCLab/PPOCRLabel#56]
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/home/ubuntu/miniconda3/envs/ppocrlabel/bin/platforms" ...
loaded library "/home/ubuntu/miniconda3/envs/ppocrlabel/lib/python3.12/site-packages/cv2/qt/plugins/platforms/libqxcb.so"
QObject::moveToThread: Current thread (0x1116a50) is not the object's thread (0x63c2d10).
Cannot move to target thread (0x1116a50)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ubuntu/miniconda3/envs/ppocrlabel/lib/python3.12/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by GreatV** [comment]
降低一下python版本试试

**Comment by kezidanbao** [comment]
我使用python3.8成功起来了
![image](https://github.com/user-attachments/assets/c4b39062-c5d2-443d-b863-9467c9200faa)

**Comment by GreatV** [comment]
估计是没有中文字体吧

**Comment by kezidanbao** [comment]
是的，ubuntu系统无中文字体。感谢大佬
确实字体参考：https://blog.csdn.net/mygodalien/article/details/126882525
