### ISSUE TITLE
表格标注生成的gt.txt文件里面的gt属性值html页面表格样式不匹配的bug

### ISSUE THREAD

**Issue by freezehe** [PFCCLab/PPOCRLabel#57]
各位老师好，我在标注表格的时候发现一个问题麻烦帮忙解答一下。我标注的是一个简单的表格，在学习完了表格标注培训视频，参考着标注，顺序也调整正确，生成的gt.txt里面的gt的属性值，我复制粘贴到一个txt文本转为html页面查看的时候，发现表格没有对应上样式。我贴一下我上述涉及到的图片和标注文件gt.txt
[gt.txt](https://github.com/user-attachments/files/16755467/gt.txt)
![image](https://github.com/user-attachments/assets/7e30b10f-1736-404e-a6cc-b887072ce188)
![image](https://github.com/user-attachments/assets/20b109a0-4646-4286-ac6c-8c9759c945c3)
我想问一下，这个是不是一个bug？因为gt的属性值对应的是html页面，没有跟表格样式对应上。

**Comment by GreatV** [comment]
原图提供一下

**Comment by freezehe** [comment]
原图
![Uploading 2.jpg…]()

**Comment by freezehe** [comment]
> 原图提供一下

![image](https://github.com/user-attachments/assets/9a6fcc89-ca58-485a-835f-dce24b678e8d)

**Comment by freezehe** [comment]
我的版本：
![image](https://github.com/user-attachments/assets/7083e040-04f5-4513-82f1-f0b2d9f78673)

**Comment by GreatV** [comment]
这个后面我看看怎么优化一下
