### ISSUE TITLE
编译完无法启动

### ISSUE THREAD

**Issue by Andyszl** [PFCCLab/PPOCRLabel#62]
编译完成后
![image](https://github.com/user-attachments/assets/aafcaaa1-e2d5-426f-991b-368d05fdd5a6)

![image](https://github.com/user-attachments/assets/36332fee-a5d3-4d0b-812d-30731f9c15c6)

运行 PPOCRLabel.exe --lang ch，鼠标转了会圈就没有任何反应了

**Comment by GreatV** [comment]
python版本可以运行吗

**Comment by Andyszl** [comment]
> python版本可以运行吗

 python PPOCRLabel.py --lang ch
Traceback (most recent call last):
  File "C:\Users\Administrator\PPOCRLabel-main\PPOCRLabel.py", line 74, in <module>
    from libs.resources import newIcon
ImportError: cannot import name 'newIcon' from 'libs.resources' (C:\Users\Administrator\PPOCRLabel-main\libs\resources.py)

**Comment by GreatV** [comment]
https://github.com/PFCCLab/PPOCRLabel#124-pyinstaller-build

是不是少了一步
```
pyrcc5 -o libs/resources.py resources.qrc
```
