### ISSUE TITLE
Windows自动保存未提交变更卡死，其他平台应该也有这个问题

### ISSUE THREAD

**Issue by houjiaxxin** [PFCCLab/PPOCRLabel#88]
卡死情况描述：
1、要启用自动保存未提交变更
2、如果过程中使用删除图像功能
3、会导致卡死
初步怀疑是删除图像后未更新自动保存列表导致索引不存在导致的bug

**Comment by GreatV** [comment]
可以先切到2.1.8版本

**Comment by yes-github** [comment]
> 卡死情况描述： 1、要启用自动保存未提交变更 2、如果过程中使用删除图像功能 3、会导致卡死 初步怀疑是删除图像后未更新自动保存列表导致索引不存在导致的bug

已修复，请更新最新版
