### ISSUE TITLE
Linux issued when run PPOCRLabel

### ISSUE THREAD

**Issue by audihop354** [PFCCLab/PPOCRLabel#91]
If you guy have install Paddle and PPOCRLabel on linux and have this issued.
![2024-09-29_13-25](https://github.com/user-attachments/assets/29919efd-45de-4af7-98c2-f77a14a1b9b8)
you should try unistall opencv-python and install opencv-python-headless

like this 
$ pip uninstalll opencv-python
$ pip install opencv-python-headless

That work well for me, thanks

**Comment by audihop354** [comment]
any idea to fix this when install can share, maybe because my machine not work with that opencv LOL

**Comment by blizaga** [comment]
same issue
