### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by phnguynmkhoi** [PFCCLab/PPOCRLabel#93]
If you get a warnings like that when trying to run on ubuntu:
![Image](https://github.com/user-attachments/assets/d97818f0-90b5-41ba-ae8b-7eddc9518626)
Definitely you miss some lib in your OS. Try running the following command:
``` sudo apt install libxcb-xinerama0 ```

**Comment by audihop354** [comment]
Maybe it go wrong because you are using Wayland instead of X11. For anyone who use X11.
Just unistall opencv-python
`pip unistall opencv-python`
and install opencv-python-headless instead
`pip install opencv-python-headless`

**Comment by phnguynmkhoi** [comment]
> Maybe it go wrong because you are using Wayland instead of X11. For anyone who use X11. Just uninstall opencv-python `pip uninstall opencv-python` and install opencv-python-headless instead `pip install opencv-python-headless`

I've tried but still get the error :vv

**Comment by Jiang7Ting** [comment]
annoying error，i had no way to solve

**Comment by GreatV** [comment]
hi @phnguynmkhoi @Jiang7Ting Try these steps:

```shell
pip uninstall opencv-python
pip uninstall opencv-contrib-python

pip install opencv-python-headless
```
![Image](https://github.com/user-attachments/assets/eb2e1d7a-7217-41a3-9fe4-8afe67008a37)

- https://github.com/PaddlePaddle/Paddle/issues/29507
- https://stackoverflow.com/questions/69994530/qt-qpa-plugin-could-not-find-the-qt-platform-plugin-wayland

**Comment by Jiang7Ting** [comment]
thankyou



---Original---
From: "Wang ***@***.***&gt;
Date: Sun, Oct 27, 2024 11:49 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PFCCLab/PPOCRLabel] qt.qpa.plugin: Could not load the Qtplatform plugin "xcb" in "" even though it was found. (Issue #93)




 
hi @phnguynmkhoi @Jiang7Ting Try these steps:
 pip uninstall opencv-python pip uninstall opencv-contrib-python pip install opencv-python-headless
 
image.png (view on web)
  
PaddlePaddle/Paddle#29507
 
https://stackoverflow.com/questions/69994530/qt-qpa-plugin-could-not-find-the-qt-platform-plugin-wayland
