### ISSUE TITLE
Apple m2 pro运行后无法打开窗口，程序没有响应

### ISSUE THREAD

**Issue by idonthavename** [PFCCLab/PPOCRLabel#95]
版本信息
macos：15.0.1 (24A348)
python：3.9.6
paddleocr：2.9.0
paddlepaddle：2.6.1
PyQt5：5.15.11

问题截图
![Image](https://github.com/user-attachments/assets/68ec845c-2d60-4f24-aa6f-f7fe4b81bb11)

**Comment by GreatV** [comment]
paddleocr 2.8.1可以吗

**Comment by idonthavename** [comment]
> paddleocr 2.8.1可以吗

还是打不开.

**Comment by GreatV** [comment]
paddle框架安装的是arm版本还是x86版本

**Comment by idonthavename** [comment]
> paddle框架安装的是arm版本还是x86版本

paddle换成3.0.0b1可以运行了，感谢帮助。
但官网显示不能使用，容易误导，建议改正
![Image](https://github.com/user-attachments/assets/99846a94-7326-4cc7-9c1c-1a90b0c44f63)

**Comment by GreatV** [comment]
@idonthavename 已反馈给相关人员。
