### ISSUE TITLE
建议给出PPOCRLabel安装说明

### ISSUE THREAD

**Issue by UWPStone** [PFCCLab/PPOCRLabel#96]
目前因用 python 3.9.0   python 3.10 ，自动安装PPOCRLabel后使用时出现异常：

python 3.9.0 ：
      initPos PyQt5.QtCore.QPointF(1203.0, 279.8076923076923)   Can not recognise the box

python 3.10 

 "c:\ProgramData\miniconda3\envs\paddlex\Lib\site-packages\PPOCRLabel\libs\canvas.py", line 587, in paintEvent
    shape.paint(p)
  File "c:\ProgramData\miniconda3\envs\paddlex\Lib\site-packages\PPOCRLabel\libs\shape.py", line 183, in paint
    painter.drawText(min_x, min_y, self.label)
TypeError: arguments did not match any overloaded call:
  drawText(self, p: Union[QPointF, QPoint], s: Optional[str]): argument 1 has unexpected type 'float'
  drawText(self, rectangle: QRectF, flags: int, text: Optional[str]): argument 1 has unexpected type 'float'
  drawText(self, rectangle: QRect, flags: int, text: Optional[str]): argument 1 has unexpected type 'float'
  drawText(self, rectangle: QRectF, text: Optional[str], option: QTextOption = QTextOption()): argument 1 has unexpected type 'float'
  drawText(self, p: QPoint, s: Optional[str]): argument 1 has unexpected type 'float'
  drawText(self, x: int, y: int, width: int, height: int, flags: int, text: Optional[str]): argument 1 has unexpected type 'float'
  drawText(self, x: int, y: int, s: Optional[str]): argument 1 has unexpected type 'float'
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::translate: Painter not active
QPainter::worldTransform: Painter not active
QWidgetEffectSourcePrivate::pixmap: Painter not active
QPainter::save: Painter not active
QPainter::setOpacity: Painter not active
QPainter::setWorldTransform: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::begin: Painter already active

建议给出安装说明，谢谢

**Comment by GreatV** [comment]
参考 https://github.com/PFCCLab/PPOCRLabel#1-installation-and-run

**Comment by UWPStone** [comment]
python3.9  python3.10  环境下同样的安装步骤：

1.1 Install PaddlePaddle
         pip3 install --upgrade pip
         python -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu123/

1.2 Install and Run PPOCRLabel
        pip install PPOCRLabel  # install 

        # Select label mode and run
        python PPOCRLabel.py --lang ch --kie True --gpu


在此前我安装了PaddleX：
参考：
    https://github.com/PaddlePaddle/PaddleX/discussions/1849
   https://mp.weixin.qq.com/s/5weZTqmhNeG6n9joneQnCA

    CUDA版本：12.3
    CUDNN版本: cudnn-windows-x86_64-8.9.7.29_cuda12-archive.zip
    Python版本：3.10
       
  从 Gitee clone 源码
     git clone  https://gitee.com/paddlepaddle/PaddleX.git
  
PyQt5                     5.15.11
opencv-python             4.5.5.64
opencv-contrib-python     4.6.0.66
paddleocr                 0.1.0.dev1+g7bac051.d20241024
paddlepaddle-gpu          3.0.0b1
PPOCRLabel                  2.1.10

**Comment by GreatV** [comment]
你这个是成功了还是失败了

**Comment by UWPStone** [comment]
安装都是成功的，使用过程中有报错。

**Comment by UWPStone** [comment]
shape.py", line 183,   参考其他已解决的issues:  修改为int .    python 3.10   可以了 。

普通标注试过， 
我一般用  python PPOCRLabel.py --lang ch --kie True --gpu

**Comment by GreatV** [comment]
欢迎提交一个PR把你的修改同步到仓库里来

**Comment by UWPStone** [comment]
怎么提交 ？ 我不会。

**Comment by GreatV** [comment]
网上搜搜一下
