### ISSUE TITLE
python version for PPOCRLabel

### ISSUE THREAD

**Issue by blizaga** [PFCCLab/PPOCRLabel#97]
Please provide instructions for installing the correct python version in the README section, the supported version for PPOCRLabel is currently only for python version 3.8.

**Comment by GreatV** [comment]
work well on python3.10

**Comment by blizaga** [comment]
oh really?

Can you provide instructions for using the correct python version, I was using python version 3.11 yesterday and it didn't work at all. Since I'm also not Chinese, I'm having trouble reading the issues that have been answered in this repo.
